# Prometheus Gateway Configuration

providers:
  - name: "openai"
    api_key_env: "OPENAI_API_KEY"
    models:
      - "gpt-4o"
      - "gpt-4o-mini"
      - "gpt-3.5-turbo"

  - name: "google"
    api_key_env: "GOOGLE_API_KEY"
    models:
      - "gemini-2.5-flash"
      - "gemini-2.5-flash-lite-preview-06-17"
      - "gemini-2.5-pro"

  - name: "anthropic"
    api_key_env: "ANTHROPIC_API_KEY"
    models:
      - "claude-opus-4-20250514"
      - "claude-sonnet-4-20250514"
      - "claude-3-7-sonnet-latest"