# docker-compose.yml (API Gateway)
services:
  redis:
    image: redis:alpine
    networks:
      - shared-app-network

  gateway:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - shared-app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gateway
    networks:
      - shared-app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - shared-app-network

# volumes:
#   gateway_db:

networks:
  shared-app-network:
    external: true
