global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000'] # 'gateway' is the service name in docker-compose